### ISSUE TITLE
java.lang.NoSuchMethodError: No static method - AnimatedContent 

### ISSUE THREAD

**Issue by ferenczAndras** [hi-manshu/Kalendar#162]
```
java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Ljava/lang/String;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~ld90tcC92DCwdfLxq_5ZEg==/com.coachpass.h2oTeam-pl-p1A2QOnPKYKUPzRpTpw==/base.apk)
                                                                                                    	at com.himanshoe.kalendar.ui.component.header.KalendarHeaderKt.KalendarHeader(KalendarHeader.kt:87)
                                                                                                    	at com.himanshoe.kalendar.ui.oceanic.KalendarOceanicKt.KalendarOceanic(KalendarOceanic.kt:120)
```

Hi, I am using Compose 1.5.1 and I am getting this error for KalendarOceanic. 

I love this library. amazing!

**Comment by ctb0k33** [comment]
i ran into the same problem. Have you had the solution yet.

**Comment by gsrathoreniks** [comment]
Can you share a sample to reproduce this?
